import {readFileSync} from 'node:fs';
import assert from 'node:assert/strict';
import vm from 'node:vm';
const src=readFileSync(new URL('../../index.html',import.meta.url),'utf8');
const grab=name=>{const m=src.match(new RegExp('window\\.'+name+' = function[\\s\\S]*?\\n\\};'));assert(m);return m[0];};
const events=new Map(),page={id:'page-home'},modal={parentElement:page,style:{display:'flex'}};
let mounts=0;
const body={appendChild(el){el.parentElement=this;mounts++;}};
const vv={height:700,offsetTop:0,addEventListener(k,f){events.set('vv:'+k,f);},removeEventListener(k,f){assert.equal(events.get('vv:'+k),f);events.delete('vv:'+k);}};
const window={visualViewport:vv,innerHeight:700,addEventListener(k,f){events.set(k,f);},removeEventListener(k,f){assert.equal(events.get(k),f);events.delete(k);}};
const document={body,getElementById:()=>modal};
vm.runInNewContext(grab('_cropViewportStart')+grab('_cropViewportStop'),{window,document});
window._cropViewportStart();assert.equal(modal.parentElement,body);assert.equal(modal.style.height,'700px');assert.equal(modal.style.top,'0px');
window._cropViewportStart();assert.equal(mounts,1);assert.equal(events.size,3,'단계 전환마다 리스너 중복 금지');
vv.height=350;vv.offsetTop=90;events.get('vv:resize')();assert.equal(modal.style.top,'90px');assert.equal(modal.style.height,'350px');
assert.equal(modal.style.bottom,'auto');assert.equal(modal.style.maxHeight,'none');
vv.height=0;events.get('vv:resize')();assert.equal(modal.style.height,'350px');
window._cropViewportStop();assert.equal(events.size,0);assert.equal(window._cropViewportFit,null);
window._cropViewportStop();
window.visualViewport=null;window.innerHeight=640;window._cropViewportStart();assert.equal(modal.style.top,'0px');assert.equal(modal.style.height,'640px');
window._cropViewportStop();assert.equal(events.size,0);
assert(/function _setCropStep\(step\)\s*\{\s*if \(window\._cropViewportStart\)/.test(src),'모든 업로드 진입 경로에서 portal/viewport 초기화');
const close=src.match(/function closeCropModal\(\)[\s\S]*?\n\}/)[0];
assert(close.indexOf('focused.blur()')<close.indexOf('unlockBodyScroll()'),'입력 포커스 해제 후 스크롤 복원');
assert(close.indexOf('_cropViewportStop()')<close.indexOf('unlockBodyScroll()'),'닫는 도중 viewport 리스너 중지');
console.log('OK crop-scroll-viewport: body portal, viewport/keyboard geometry, idempotent listeners, close cleanup');
